Support custom plugin extension
sofastack/sofa-ark pull request #429
Opened 2020-12-14 13:37 UTC by glmapper

#390 support plugin to extension the business dependency

2020-12-16 02:29 UTC, ujjboy requested changes

2020-12-16 02:29 UTC, ujjboy commented on sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java
> +            item.setVersion(artifact.split(":")[1]);
这里改成 split一次吧

2020-12-16 02:29 UTC, ujjboy commented on sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java
> +                        writer.writeNestedLibrary(destination + "export/", library);
这种判断会不会有问题，例如 'xxx-1.0.jar' 和 'xxx-a-1.0.jar'

2020-12-16 02:29 UTC, ujjboy commented on sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java
> +        return sb.toString().substring(0, sb.length() - delimiter.length());
不用先 toString()

2020-12-16 02:29 UTC, ujjboy commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +        java.util.List<URL> preRemoveList = new ArrayList<>();
这几个 java.util.  都去一下

2020-12-16 02:29 UTC, ujjboy commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +        if (StringUtils.isEmpty(excludeArtifact) || extensions == null) {
这里应该是 && ？

2020-12-16 02:29 UTC, ujjboy commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +        for (int i = 0; i < objects.length; i++) {
使用 
urls = new URL[objects.length];
urlList.toArray(urls)  就可以了

2020-12-16 02:29 UTC, ujjboy commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
> +        return dependencies;
就当前这段逻辑来说，换成下面的写法更好一些
if (StringUtils.strToSet(injectPluginDependencies, Constants.MANIFEST_VALUE_SPLIT) != null) {
            dependencies.addAll(StringUtils.strToSet(injectPluginDependencies,
            Constants.MANIFEST_VALUE_SPLIT));
        }
        return dependencies;

2020-12-16 09:41 UTC, glmapper commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
> +        this.injectExportPackages = StringUtils.strToSet(injectExportPackages,
这个是 BizModel 里面持有的属性，get&set 方法用于提供对外获取属性，ark 中暂无依赖此属性的地方

2020-12-16 09:42 UTC, glmapper commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
> +        this.injectExportPackages = StringUtils.strToSet(injectExportPackages,
是从打包插件 config 中设置传递过来的

2020-12-16 09:55 UTC, glmapper commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +        if (StringUtils.isEmpty(excludeArtifact) || extensions == null) {
这里是 || 操做，配置和额外的jar 必须同时提供才能生效，如果任一不满足，则不会执行扩展 url 逻辑

2020-12-18 11:09 UTC, ujjboy approved these changes
LGTM

2020-12-21 02:33 UTC, ujjboy approved these changes
LGTM

2020-12-21 02:51 UTC, merged