support extension excludes denpendencies from extra resources
sofastack/sofa-ark pull request #430
Opened 2020-12-15 12:08 UTC by glmapper

2020-12-16 02:52 UTC, ujjboy requested changes

2020-12-16 02:52 UTC, ujjboy commented on sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
> +                    String dataLine = bufferedReader.readLine();
这个文件只读一行？

2020-12-18 10:52 UTC, ujjboy requested changes

2020-12-18 10:52 UTC, ujjboy commented on sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
> +            extensionExcludeArtifacts(baseDir + "/" + ARK_CONF_BASE_DIR + "/" + packExcludesConfig);
/ 是不是换成 File.separator ？

2020-12-18 10:52 UTC, ujjboy commented on sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
> +                while (!StringUtils.isEmpty(dataLine)) {
读到空行就跳出， 手误文件里有空行的行会不会有问题

2020-12-18 10:52 UTC, ujjboy commented on sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
> +                    } else if (dataLine.startsWith("excludeGroupIds")) {
这几个字符串变成常量吧

2020-12-21 02:49 UTC, alaneuler approved these changes
LGTM

2020-12-21 02:49 UTC, merged