Embed Mode: support embedPlugin class isolation
sofastack/sofa-ark pull request #530
Opened 2022-06-20 13:01 UTC by gaosaroma

### Motivation:

- support embedPlugin class isolation for **common biz** with `PLUGIN_CLASSLOADER_ENABLE=true && PLUGIN_CLASS_EXPORT_ENABLE=true` mode.
- add unit test for class isolation.

### Modification:

- modify pluginFactoryServiceImp#createEmbedPlugin

### Result:

Fixes #496 .

2022-06-24 09:23 UTC, yuanyuancin commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +                enableExportClass ? getFinalPluginUrls(pluginArchive, null, plugin.getPluginName())
不能用enableExportClass来判断，需要一个新的属性

2022-06-24 09:23 UTC, yuanyuancin commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +                    .getClassPath()) : masterClassLoader)
同上

2022-06-25 08:33 UTC, gaosaroma commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +                enableExportClass ? getFinalPluginUrls(pluginArchive, null, plugin.getPluginName())
在embed模式下，新增了属性`PLUGIN_CLASSLOADER_ENABLE`，默认是`false`；开启`PLUGIN_CLASSLOADER_ENABLE=true`和`PLUGIN_CLASS_EXPORT_ENABLE=true`之后，embed模式可实现plugin的类隔离。

2022-06-25 08:34 UTC, gaosaroma commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +                    .getClassPath()) : masterClassLoader)
同上

2022-06-28 03:19 UTC, glmapper requested changes

2022-06-28 03:19 UTC, glmapper commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +            .getProperty(PLUGIN_CLASSLOADER_ENABLE));
这里为什么不使用 ArkConfigs

2022-06-28 03:19 UTC, glmapper commented on sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoaderTest.java
> -        //        BizClassLoader bizClassLoader = new BizClassLoader("mock:1.0", ucp.getURLs());
删除这些注释的代码

2022-06-28 03:19 UTC, glmapper commented on sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
> +            "web-ark-plugin", "config-ark-plugin", "sofaboot-ark-plugin",
BASE_ARK_PLUGIN 可能不能这么定义，外部用户也完全可以自定义这些 plugin，应该允许扩展

2022-06-28 03:36 UTC, zjulbj commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +            .setPluginClassLoader(
enablePluginClassLoader && isNotBaseArkPlugin这个判断出现了两次，这里是否可以合并下，先算好classpath和pluginclassloader，再set进去

2022-06-28 03:37 UTC, zjulbj commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +        for (String baseName : Constants.BASE_ARK_PLUGIN) {
这里是否可以支持扩展？通过plugin的扩展属性来判断？

2022-06-28 05:55 UTC, glmapper commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +                enableExportClass ? getFinalPluginUrls(pluginArchive, null, plugin.getPluginName())
> embed模式可实现plugin的类隔离

这个描述有问题，plugin 本身就是隔离的

2022-06-28 07:58 UTC, gaosaroma commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +                enableExportClass ? getFinalPluginUrls(pluginArchive, null, plugin.getPluginName())
修改为：embed模式下，开启`PLUGIN_CLASSLOADER_ENABLE=true`和`PLUGIN_CLASS_EXPORT_ENABLE=true`之后，可**开启**plugin的类隔离

2022-06-28 07:59 UTC, gaosaroma commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +            .getProperty(PLUGIN_CLASSLOADER_ENABLE));
已修改

2022-06-28 07:59 UTC, gaosaroma commented on sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoaderTest.java
> -        //        BizClassLoader bizClassLoader = new BizClassLoader("mock:1.0", ucp.getURLs());
嗯，这是删除的之前的注释

2022-06-28 08:04 UTC, gaosaroma commented on sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
> +            "web-ark-plugin", "config-ark-plugin", "sofaboot-ark-plugin",
新增plugin属性`delegateToEmbedBase`，默认为`false`，用户可自定义该属性；在Embed模式中开启`PLUGIN_CLASSLOADER_ENABLE=true`之后，当`delegateToEmbedBase=true`时，该plugin将委托嵌入基座进行类、包、资源的加载，否则将使用自己的pluginClassLoader进行加载。

2022-06-28 08:05 UTC, gaosaroma commented on sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
> +            .setPluginClassLoader(
好的，设置了`usePluginClassLoader = enablePluginClassLoader && !delegateToEmbedBase`。

2022-06-28 08:12 UTC, gaosaroma commented
其它问题：对于动态部署示例（https://github.com/sofastack-guides/sofa-ark-dynamic-guides），在embed模式开启类隔离的使用中，需要其依赖runtime-sofa-boot-plugin设置属性`<delegateToEmbedBase>true</delegateToEmbedBase>`；或许PR完成后再给runtime-sofa-boot-plugin提issue？

2022-06-28 08:54 UTC, zjulbj approved these changes
LGTM

2023-03-20 03:04 UTC, lylingzhen commented
该 PR 还需要再充分讨论一下，暂时不合并，待 5 月份重新讨论再决定 close 还是 approve。

2023-11-04 02:04 UTC, closed without merging