feat(ark springboot): support  springboot1
sofastack/sofa-ark pull request #760
Opened 2023-10-25 09:16 UTC by qixiaobo

https://github.com/sofastack/sofa-ark/issues/268
support springboot1

### Motivation
支持springboot1客户 
模块化势必涉及到大量的存量应用
而存量长尾应用很多springboot1版本

### Modification

支持springboot1 模块中添加相对应的EmbeddedServletContainer支持

### Result

Resolved or fixed [#268  ](https://github.com/sofastack/sofa-ark/issues/268)

2023-11-03 08:13 UTC, lvjing2 commented
代码看过了，基本 OK，就还需要补充下单测。

2023-11-07 16:26 UTC, glmapper requested changes

2023-11-07 16:26 UTC, glmapper commented on sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainer.java
> +import org.apache.catalina.*;
避免使用.*

2023-11-07 16:26 UTC, glmapper commented on sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainer.java
> +        logger.info("Tomcat initialized with port(s): " + getPortsDescription(false));
使用占位符代替字符串拼接

2023-11-07 16:26 UTC, glmapper commented on sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainer.java
> +                stopSilently();
这里是否可以考虑将范围扩大到外层去

2023-11-07 16:26 UTC, glmapper commented on sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainer.java
> +            logger.error("Cannot pause connector: ", ex);
同上，日志打印要规范一些

2023-11-07 16:26 UTC, glmapper commented on sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainerFactory.java
> +import org.apache.catalina.*;
同上

2023-11-07 16:26 UTC, glmapper commented on sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainerFactory.java
> +                context.setResources(new StandardRoot(context));
这里的条件docmentRoot和下面的StandandRoot看起来没有什么必要联系？

2023-11-08 08:52 UTC, qixiaobo commented on sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainer.java
> +import org.apache.catalina.*;
超过5个以上的类还是建议保留*

2023-11-08 08:57 UTC, qixiaobo commented on sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainer.java
> +        logger.info("Tomcat initialized with port(s): " + getPortsDescription(false));
这边代码主要参考tomcat 还是优先保留tomcat的format 避免出现将来升级改动过多

2023-11-08 08:58 UTC, qixiaobo commented on sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainer.java
> +                stopSilently();
同上哈

2023-11-08 09:02 UTC, qixiaobo commented on sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainerFactory.java
> +                context.setResources(new StandardRoot(context));
要判断当documentRoot不存在的时候去做一些事情

2023-11-09 01:06 UTC, glmapper requested changes

2023-11-09 01:06 UTC, glmapper commented on sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainer.java
> +import org.apache.catalina.startup.Tomcat;
那你这些应该也属于 * 范畴?
--
import org.apache.catalina.*;
import org.apache.catalina.connector.Connector;
import org.apache.catalina.startup.Tomcat;
--

2023-11-09 01:06 UTC, glmapper commented on sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainer.java
> +import org.apache.catalina.startup.Tomcat;
还有其他诸如 org.springframework.boot..xx.xx 也没有按照超过 5 个保留 * 的方式来组织

2023-11-09 05:43 UTC, qixiaobo commented on sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainer.java
> +import org.apache.catalina.startup.Tomcat;
*我没记错是不包含子包的吧 所以那个还是需要的
![image](https://github.com/sofastack/sofa-ark/assets/2881751/72197756-4b0f-44e6-a22c-6a068a1c8787)

2023-11-10 06:04 UTC, lvjing2 approved these changes
LGTM

2023-11-10 16:47 UTC, glmapper commented
LGTM

2023-11-10 17:42 UTC, merged